name: Update Version

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Extract release version
      id: get_release_version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Update setup.py version
      run: |
        sed -i "s/version='.*'/version='${{ env.RELEASE_VERSION }}'/" setup.py

    - name: Verify changes
      run: cat setup.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add setup.py
        git commit -m "Update version to ${{ env.RELEASE_VERSION }}"
        git push origin HEAD

    - name: Trigger Publish Workflow
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"publish"}'